# ============================================
# MARMORARIA - application.properties
# ============================================
server.port=8080

# --- H2 (banco em memória - para rodar sem MySQL) ---
#spring.datasource.url=jdbc:h2:mem:marmoraria;DB_CLOSE_DELAY=-1;MODE=MySQL
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# --- MySQL (descomentar quando tiver MySQL instalado) ---
 spring.datasource.url=jdbc:mysql://localhost:3306/marmoraria?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
 spring.datasource.username=root
 spring.datasource.password=Ld777Pur&@moR
 spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
